name: Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - run: nuget restore ysonet.sln
      - uses: microsoft/setup-msbuild@v1.3.1
      - run: msbuild ysonet.sln -p:Configuration=Release
      - run: |
          mkdir release
          move .\ysonet\bin\Release .\release
      - uses: actions/upload-artifact@v4
        with:
          name: ysonet-${{ github.sha }}
          path: .\release
