name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore ysoserial.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build solution
        run: msbuild ysoserial.sln -p:Configuration=Release

      - name: Create artifact directory
        run: |
          mkdir release
          move .\ysoserial\bin\Release .\release

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: ysoserial-${{ github.sha }}
          path: .\release
